#pragma once

namespace divoomdev::divoom {

enum ErrorCode {
  OK = 0,
  HTTP_NORMAL_ERROR = 1,
  HTTP_REGISTER_ERROR1 = 2,
  HTTP_REGISTER_ERROR2 = 3,
  HTTP_LOGIN_ERROR_NO_USER = 4,
  HTTP_LOGIN_ERROR_PASSWORD = 5,
  HTTP_ADD_BUDDY_ERROR = 6,
  HTTP_GET_ERROR = 7,
  HTTP_ERROR_CAN_NOT_MATCH = 8,
  HTTP_ERROR_CAN_NOT_DEAL_WITH = 9,
  HTTP_ERROR_WRONG_CMD = 10,
  HTTP_ERROR_TOKEN_MISSMATCH = 11,
  HTTP_REQUEST_EMPTY = 12,
  HTTP_REQUEST_JSON_ERROR = 13,
  HTTP_BUDDY_HAD_FRIEND = 14,
  HTTP_HAD_NOT_FRIEND = 15,
  HTTP_GALLERY_UPLOAD_ERROR = 16,
  HTTP_PHONE_FORMAT_ERROR = 17,
  HTTP_PHONE_CHECK_ERROR = 18,
  HTTP_TOO_MATCH = 19,
  HTTP_NEED_CHECK = 20,
  BLACK_ERROR = 21,
  LIMIT_UPLOAD = 22,
  FORBIDEN_ERROR = 23,
  BLUETOOTH_PASSWORD_ERROR = 24,
  HTTP_LOCK_ACCOUNT = 25,
  HTTP_UPLOAD_TEXT_TO_SERVER = 26,
  HTTP_SUCCESS = 27,
};

}  // namespace divoomdev::divoom
